export const martialWeaponOptions = [
  "Battleaxe",
  "Flail",
  "Glaive",
  "Greataxe",
  "Greatsword",
  "Halberd",
  "Lance",
  "Longsword",
  "Maul",
  "Morningstar",
  "Pike",
  "Rapier",
  "Scimitar",
  "Shortsword",
  "Trident",
  "War Pick",
  "Warhammer",
  "Whip",
  "Blowgun",
  "Hand Crossbow",
  "Heavy Crossbow",
  "Longbow",
].map((name) => ({
  value: name,
  label: name,
}));
