export const skillProficiencies = [
  { value: "Acrobatics", label: "Acrobatics" },
  { value: "AnimalHandling", label: "AnimalHandling" },
  { value: "Arcana", label: "Arcana" },
  { value: "Athletics", label: "Athletics" },
  { value: "Deception", label: "Deception" },
  { value: "History", label: "History" },
  { value: "Insight", label: "Insight" },
  { value: "Intimidation", label: "Intimidation" },
  { value: "Investigation", label: "Investigation" },
  { value: "Medicine", label: "Medicine" },
  { value: "Nature", label: "Nature" },
  { value: "Perception", label: "Perception" },
  { value: "Performance", label: "Performance" },
  { value: "Persuasion", label: "Persuasion" },
  { value: "Religion", label: "Religion" },
  { value: "SleightOfHand", label: "SleightOfHand" },
  { value: "Stealth", label: "Stealth" },
  { value: "Survival", label: "Survival" },
];
