export const initialCharacterState = {
  name: "",
  characterClass: {
    name: "",
    description: "",
    hitDice: "",
    primaryAbility: [],
    savingThrowProficiencies: [],
    armorProficiencies: [],
    weaponProficiencies: [],
    toolProficiencies: [],
    skillProficiencies: [],
    startingEquipment: [],
    classFeatures: [],
    subclasses: [],
    spellcasting: {
      spellcastingAbility: "",
      cantripsKnown: [],
      spellsKnown: [],
      spellSlots: [],
      spellList: [],
    },
  },
  race: { name: "" },
  background: {
    name: "",
    description: "",
    equipment: [],
    languages: [],
    skillProficiencies: [],
    toolProficiencies: [],
    featureName: "",
    featureDescription: "",
    personalityTraits: "",
    ideals: "",
    bonds: "",
    flaws: "",
  },
};
